using System.Diagnostics;
using System.Globalization;
using System.Text.Json;
using DuckDB.NET.Data;

namespace Meridian.Bench.Scale;

/// <summary>Shape of a synthetic dataset: metrics × entities × days × readings per day.</summary>
public sealed record DatasetSpec(int Entities, int Metrics, int Days, int PerDay, int GapPercent)
{
    public static readonly DateTime Start = new(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc);

    public long Slots => (long)Metrics * Entities * Days * PerDay;
    public DateTime End => Start.AddDays(Days);
}

/// <summary>What was generated, written next to the Parquet files so a run knows the data's shape.</summary>
public sealed record DatasetManifest(DatasetSpec Spec, long Rows, long Bytes, double GenerateSeconds, string DuckDbVersion);

/// <summary>
/// Writes a synthetic longitudinal dataset to Parquet entirely inside DuckDB — rows are generated by SQL
/// and streamed to disk, so a billion rows never touch .NET memory. Values are a weekly cycle plus noise,
/// deterministic (hash-based, not random()) so the same spec always produces the same data. Rows come out
/// ordered by metric → entity → time, which keeps Parquet row-group min/max tight for entity filtering.
/// </summary>
public static class Generator
{
    public static DatasetManifest Generate(DatasetSpec spec, string outDir)
    {
        if (86400 % spec.PerDay != 0) throw new ArgumentException("--per-day must divide 86400 (e.g. 1, 2, 4, 24, 96).");
        Directory.CreateDirectory(outDir);
        var parquetDir = Path.Combine(outDir, "datapoints");
        if (Directory.Exists(parquetDir)) Directory.Delete(parquetDir, recursive: true);

        string I(long v) => v.ToString(CultureInfo.InvariantCulture);
        long perSeries = (long)spec.Days * spec.PerDay;
        long perMetric = perSeries * spec.Entities;
        int secondsPerReading = 86400 / spec.PerDay;

        var sql = $"""
            COPY (
                SELECT
                    'metric-' || CAST(i // {I(perMetric)} AS VARCHAR)                         AS metric,
                    CAST((i // {I(perSeries)}) % {I(spec.Entities)} + 1 AS BIGINT)            AS entity_id,
                    TIMESTAMP '2024-01-01' + to_seconds(CAST((i % {I(perSeries)}) * {I(secondsPerReading)} AS BIGINT)) AS ts,
                    CASE WHEN hash(i * 7 + 1) % 500 = 0 THEN NULL
                         ELSE round(60
                              + 20 * sin(2 * pi() * ((i % {I(perSeries)}) / {I(spec.PerDay)}.0) / 7.0 + (i // {I(perSeries)}) % 97)
                              + (hash(i) % 2000) / 100.0 - 10, 3)
                    END                                                                        AS value
                FROM range({I(spec.Slots)}) AS t(i)
                WHERE hash(i * 13 + 5) % 100 >= {I(spec.GapPercent)}
            ) TO '{ToSqlPath(parquetDir)}' (FORMAT parquet, COMPRESSION zstd, PARTITION_BY (metric), ROW_GROUP_SIZE 1000000);
            """;

        var sw = Stopwatch.StartNew();
        using var conn = Open();
        Exec(conn, "SET preserve_insertion_order = true");
        Exec(conn, sql);
        sw.Stop();

        long rows = Scalar(conn, $"SELECT count(*) FROM {Relation(outDir)}");
        long bytes = Directory.EnumerateFiles(parquetDir, "*.parquet", SearchOption.AllDirectories).Sum(f => new FileInfo(f).Length);
        var manifest = new DatasetManifest(spec, rows, bytes, sw.Elapsed.TotalSeconds, DuckDbVersion(conn));
        File.WriteAllText(Path.Combine(outDir, "manifest.json"), JsonSerializer.Serialize(manifest, Json.Options));
        return manifest;
    }

    public static DatasetManifest ReadManifest(string dataDir) =>
        JsonSerializer.Deserialize<DatasetManifest>(File.ReadAllText(Path.Combine(dataDir, "manifest.json")), Json.Options)
        ?? throw new InvalidOperationException($"No manifest in {dataDir}. Run 'generate' first.");

    /// <summary>The relation Meridian's DuckDB source queries: the Parquet files in place, hive-partitioned
    /// by metric so a metric filter skips every other metric's files.</summary>
    public static string Relation(string dataDir) =>
        $"read_parquet('{ToSqlPath(Path.Combine(dataDir, "datapoints"))}/**/*.parquet', hive_partitioning = true)";

    public static DuckDBConnection Open()
    {
        var conn = new DuckDBConnection("Data Source=:memory:");
        conn.Open();
        return conn;
    }

    public static void Exec(DuckDBConnection conn, string sql)
    {
        using var cmd = conn.CreateCommand();
        cmd.CommandText = sql;
        cmd.ExecuteNonQuery();
    }

    public static long Scalar(DuckDBConnection conn, string sql)
    {
        using var cmd = conn.CreateCommand();
        cmd.CommandText = sql;
        return Convert.ToInt64(cmd.ExecuteScalar(), CultureInfo.InvariantCulture);
    }

    public static string DuckDbVersion(DuckDBConnection conn)
    {
        using var cmd = conn.CreateCommand();
        cmd.CommandText = "SELECT version()";
        return cmd.ExecuteScalar()?.ToString() ?? "unknown";
    }

    private static string ToSqlPath(string path) => Path.GetFullPath(path).Replace('\\', '/').Replace("'", "''");
}
