version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      test-and-build:
        patterns: ["xunit*", "Microsoft.NET.Test.Sdk", "coverlet*", "Microsoft.AspNetCore.Mvc.Testing", "BenchmarkDotNet"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
